# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\x12\x07san.p2p\"\x07\n\x05\x45mpty\"\x1b\n\x08\x45nvelope\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"0\n\x0bSyncRequest\x12\x12\n\nfrom_index\x18\x01 \x01(\x03\x12\r\n\x05limit\x18\x02 \x01(\x05\"\x1f\n\x0cSyncResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32\xcc\x01\n\x03P2P\x12\x33\n\x07Session\x12\x11.san.p2p.Envelope\x1a\x11.san.p2p.Envelope(\x01\x30\x01\x12\x33\n\x04Sync\x12\x14.san.p2p.SyncRequest\x1a\x15.san.p2p.SyncResponse\x12.\n\tBootstrap\x12\x0e.san.p2p.Empty\x1a\x11.san.p2p.Envelope\x12+\n\x06Status\x12\x0e.san.p2p.Empty\x1a\x11.san.p2p.Envelopeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_ENVELOPE']._serialized_start=31
  _globals['_ENVELOPE']._serialized_end=58
  _globals['_SYNCREQUEST']._serialized_start=60
  _globals['_SYNCREQUEST']._serialized_end=108
  _globals['_SYNCRESPONSE']._serialized_start=110
  _globals['_SYNCRESPONSE']._serialized_end=141
  _globals['_P2P']._serialized_start=144
  _globals['_P2P']._serialized_end=348
# @@protoc_insertion_point(module_scope)
