# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import p2p_pb2 as p2p__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in p2p_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class P2PStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/san.p2p.P2P/Session',
                request_serializer=p2p__pb2.Envelope.SerializeToString,
                response_deserializer=p2p__pb2.Envelope.FromString,
                _registered_method=True)
        self.Sync = channel.unary_unary(
                '/san.p2p.P2P/Sync',
                request_serializer=p2p__pb2.SyncRequest.SerializeToString,
                response_deserializer=p2p__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.Bootstrap = channel.unary_unary(
                '/san.p2p.P2P/Bootstrap',
                request_serializer=p2p__pb2.Empty.SerializeToString,
                response_deserializer=p2p__pb2.Envelope.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/san.p2p.P2P/Status',
                request_serializer=p2p__pb2.Empty.SerializeToString,
                response_deserializer=p2p__pb2.Envelope.FromString,
                _registered_method=True)


class P2PServicer:
    """Missing associated documentation comment in .proto file."""

    def Session(self, request_iterator, context):
        """Persistent bidirectional stream: handshake, gossip, staking/vote gossip,
        PING/PONG, block/transaction fetch and controller quorum votes all share
        this session, on any of the node's P2P ports.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Chain sync: one page of blocks plus a state/storage snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Bootstrap(self, request, context):
        """Peer discovery: the seed returns its signed peer records.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Peer status: chain id, genesis fingerprint, height and finality, used to
        discover the longest compatible chain before syncing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=p2p__pb2.Envelope.FromString,
                    response_serializer=p2p__pb2.Envelope.SerializeToString,
            ),
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=p2p__pb2.SyncRequest.FromString,
                    response_serializer=p2p__pb2.SyncResponse.SerializeToString,
            ),
            'Bootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.Bootstrap,
                    request_deserializer=p2p__pb2.Empty.FromString,
                    response_serializer=p2p__pb2.Envelope.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=p2p__pb2.Empty.FromString,
                    response_serializer=p2p__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'san.p2p.P2P', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('san.p2p.P2P', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class P2P:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/san.p2p.P2P/Session',
            p2p__pb2.Envelope.SerializeToString,
            p2p__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san.p2p.P2P/Sync',
            p2p__pb2.SyncRequest.SerializeToString,
            p2p__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Bootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san.p2p.P2P/Bootstrap',
            p2p__pb2.Empty.SerializeToString,
            p2p__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san.p2p.P2P/Status',
            p2p__pb2.Empty.SerializeToString,
            p2p__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
